language: node_js
before_script: if [ $IS_INTEGRATION_TEST ]; then npm run development & echo "Starting App for Integration Tests"; else echo "Not an integration test. Skipping app setup"; fi
script: npm run $TEST
addons:
  hosts:
    - bs-local.com
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: JI6B1G0O1/4gNucFWDzNJXO0HkzR9IGDZ010Lofs5ZQL/FKyTAQE/9qPjS29sumPzH3ePgsiUjddiDSn51GmmHtuxrZQD9ROT480InvDJwbs2JJfjofKFliBGoTit4tU7A8kqRNiyHYS8nmZOo/lWpAuZAp8f0zQfDOQL+G+SJFTDrHJVj3LDSbY9gLRomRn28KzZpm0vX5usQRZHpaL8LtGtq/18fOPajRHeUpZW9+ZtH3PBpcMSFFjM3QyBedKMI3i1T8Uf+FCFGifjqCoAUND6mrwOGIPcn1+RdGzFquJXKqzRu4K9HCAnjRYdbY3vqR2Ced3YzQu/UjyOuBLqpulPvpL/Y1V3SH3ufO9xUSVpyaYsfF9g+Ilzfvf2QADROl12InsdV45jB6EmVoUuGHUfFXn5jU0CqTmZ+DhOZbHU81eRXbDNnD/OPkBLzZ+x0O1t1Sv4LtE2Ha5/SSAekT5h0MQeEK5O5KffGD8V8BTm00jSxvCYxtcPMXhs9Y5HBi0oiFF37Jg1bX8ex+Ga3f81URQ4/yYKzQeDlS+TOmpk2/IevyuCbZC1A9j32NaNQxnXjSVnQ/0miINptto3hXJsq5rcGdoNDb294WMN2vb4Fx+CMLZ2++q0fvNSFWbMzSO3fp7kckDyYAsQupyc+nJlvmTMmuNpq6Uiby6ocQ=
env:
  matrix:
    - TEST="lint"
    - TEST="test:unit"
    - TEST="test:integration" ONLY_BROWSERS=chrome,firefox,safari,edge IS_INTEGRATION_TEST=true
    - TEST="test:integration" ONLY_BROWSERS=ie IS_INTEGRATION_TEST=true
  global:
    - secure: bTrwrrv7vKHQbK37c87Mx/dkjmY/oXcENsOrW8JWw1e2D5ai6fzy4miRrwRS5zG11ZC4A46Xc5hngvtf59ebGqAK9jLz+L4hr8FNy/lhHdHzn7LSeG/FOBqHtvWnO7cFGOeQmhgZMnbVLSl76HaxPis1dVo6wL5R5MY4/69eQA7JS0mmNNXNGObdYZkSuEtfMjDiQpCsg2zAUMFlKrepO+UE45oqjT9MoizUjZrMqpcJBYJtK01yIrA8TPzsA3K8pxz+ZVznpiWkp25yila5ntums16NacMlY5L5ZfaHF82ewy9vMpQDzdz+uDAm7BvzLw0ielbFEaOPr++RX8UCdvoJbbm1cCVUA2ksSkFhACKTCdeRwSIVVJOuMagZeuIiPNaTvynTBLYo4nQztzH53OH4ItYpbXBrctSsLYHAFpI5pBeoWqblHHTsAirnv+ne1DRNEj68jgFZ8twyIEEbZ7aueAHRq2Th6DVQnP88FnUvBzblavceSeW0DC/C8oCLvZ2FPWAXvHmVWuA19tl3ORdoNrs/7DrbioGWB9vp51/GQHuG1AeN5e9KeyHvnBT+CyGi/9RTyWDmlUv+6zwT1xbyFazGUd4kAif5DleerZaX4DPtXbIaMdhRZjEDc+Cv7h5QCiRCvieEd6D2IAmViR/jYuvJYlPo2eXZE384AaM=
    - secure: h5UtKrLUlR1kn7sgsU0o2UKtyf2tjc2zE4Kjwoo6rUXlxQZJsxeLQTwaDraUvxvtnX/zTlnaFnkvw5lySi0EP1CO778J3nFXVa/BbN0zaTOhL4IWEY1su8nSNSj5wq4hsT9ppPNeJBnoy92mEao8UMApBc2pP3u8EzVSmrY744vEyk8gssObYVt1YWrNKv/I0oIZXzRvF6Zg3G3QQXFs+qws0m7JXWQr8ex/46oNWi4OMY0DBkYLJvVPGVhjvvF6n2M9SmZ6/dBi6Znf4x62ibNvSeR1a5bqbZ/C5nnGUKKlGydql2irx2wSzos+e3nRfjSzB8YRcXbN72xvOPNAWqDdsD5SrKadN6WnR71HB+2XO2LxS06ClyrCjyZyUKHEMUdpuxq4pKXoXvT6ZODhJV5uLuxHuInX187syj7p3Tc60G7uqEJDuGx/QcCd1fYFnJaC3LGtuHQEQqweiH7hXqiw1WNnMmdOw4AbGxBJFrbvSe0bTfpw3rZSuwMj2aQ+Hep29nLLezJ4+u4v2UU7zjNySoPYWhuue1kmr1HqlWlTegtMGbyleumLIjHDWots9Kvv5pDS+sLCiAIu5A7vMHBCBMjIuljcYYB0Ht3QymkWEiA92RFkUMuQSA9BRmeZMHwFZKebrcWethQI4lqKIO1IzhsQKPE4+u+2qJFg3+4=
