name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run lint
      - run: npm run test:unit
      # there's a weird typescript incompatibility with jest types and mocha types
      # for whatever reason, just removing the mocha types module fixes the issue
      - run: rm -rf node_modules/@types/mocha
      - run: sudo echo "172.16.18.16 bs-local.com" | sudo tee -a /etc/hosts
      - run: npm run develoment & echo "starting test app"
      - run: ONLY_BROWSERS=chrome,firefox,safari,edge npm run test:integration
      - run: ONLY_BROWSERS=ie npm run test:integration
        env:
          CI: true
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
